---
apiVersion: v1
kind: Namespace
metadata:
  name: kino-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-admin
  namespace: kino-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin
  namespace: kino-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    namespace: kino-k8s
    name: ns-admin
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: ns-admin-token
  annotations:
    kubernetes.io/service-account.name: ns-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: kino-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
  namespace: kino-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kino-k8s
    name: cluster-admin
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cluster-admin-token
  annotations:
    kubernetes.io/service-account.name: cluster-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-pod-reader
  namespace: kino-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kino-k8s
  name: cm-pod-reader
rules:
  - apiGroups: ['']
    resources: ['pods', 'pods/log']
    verbs: ['get']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'list']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-pod-reader
  namespace: kino-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cm-pod-reader
subjects:
  - kind: ServiceAccount
    namespace: kino-k8s
    name: cm-pod-reader
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cm-pod-reader-token
  annotations:
    kubernetes.io/service-account.name: cm-pod-reader
