name: Build Frontend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  code-quality:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Mise JDX
        id: mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          echo "eval \"\$(mise activate bash)\"" >> ~/.bash_profile
          mise install node npm

      - name: Build frontend
        run: |
          cd assets
          mise x npm -- npm ci
          mise x npm -- npm run build
